### PR TITLE
Create dependabot.yml

### LINKED ISSUE #19: Getting HitHub Actions Updated Automatically
The _awesome_ tool dependabot lets you scan your used GitHub Marketplace Actions and lets you know if they are in need of an update.

The update is proposed via a pull request, which can be accepted or declined, it will itself take care of deleting pull requests if these become irrelevant.

You specify the configuration in the file: `.github/dependabot.yml` in your repository using this action - actually it scans all your actions.

```yaml
# Basic dependabot.yml file
# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
```

## Todo
- [ ] Create a PR containing one new file:   `.github/dependabot.yml`
- [ ] change the interval to a monthly update 
- [ ] make sure the action is working correctly on your fork

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #19 

## Changes made:
- Created `dependabot.yml` file for using GitHub Actions updates automatically.

### CODE REVIEW

**Comment by Rishav1707** [comment]
@Karim-53 Please review my changes...

**Comment by Karim-53** [comment]
Hi @Rishav1707 ^^

This doesn't work yet

the error is
```
[Error: .github#L1](https://github.com/Rishav1707/Compare-xAI/commit/47f1d710bf8fd7056aec18c30cba32b62e62e499#annotation_7779558219)
No event triggers defined in `on`
```
see https://github.com/Rishav1707/Compare-xAI/actions/runs/3870781978


I think the solution could be :

```
GitHub parses dependabot.yml as an action file because I put it in .github/workflows/ by mistake.
It should be .github/dependabot.yml.
``` 
from https://stackoverflow.com/questions/69446872/dependabot-error-githubl1-no-event-triggers-defined-in-on

**Comment by Karim-53** [comment]
let's also add     `open-pull-requests-limit: 10`

like in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

**Comment by Rishav1707** [comment]
> Hi @Rishav1707 ^^
> 
> This doesn't work yet
> 
> the error is
> 
> ```
> [Error: .github#L1](https://github.com/Rishav1707/Compare-xAI/commit/47f1d710bf8fd7056aec18c30cba32b62e62e499#annotation_7779558219)
> No event triggers defined in `on`
> ```
> 
> see https://github.com/Rishav1707/Compare-xAI/actions/runs/3870781978
> 
> I think the solution could be :
> 
> ```
> GitHub parses dependabot.yml as an action file because I put it in .github/workflows/ by mistake.
> It should be .github/dependabot.yml.
> ```
> 
> from https://stackoverflow.com/questions/69446872/dependabot-error-githubl1-no-event-triggers-defined-in-on

Thank you for helping me

**Comment by Rishav1707** [comment]
Is that ok now?

**Comment by Karim-53** [comment]
Thanks for your help ^^
I am not 100% sure it will work because the action did not run yet. I did merge the contribution :)
Looking forward for your upcoming contributions ?

**Pull request merged**
